-- select * from sales_table;-- 
-- Q.1 what is the total revenue generated by male vs female customers-- ?
-- select gender, SUM(purchase_amount) as revenue
-- from sales_table 
-- group by gender

-- Q.2 which customer used a discount but still spent more than the average purchase amount
select customer_id, purchase_amount
from sales_table
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount));
-- Q.3 which are the top 5 products with the highest average review ratings?
select item_purchased, ROUND(AVG(review_rating),2) as "Average Product Rating"
from sales_table
group by item_purchased
order by AVG(review_rating) desc
limit 5;
 
-- Q.4 Compare the average Purchsae Amounts between Standaed and Express Shipping
select shipping_type,
ROUND(AVG(purchase_amount),2)
from sales_table
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q.5 Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
select subscription_status ,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from sales_table
group by subscription_status
order by total_revenue,avg_spend desc;


-- Q.6 Which 5 products have the highest percentage of purchase with discounts applied?
select item_purchased ,
ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 end)/COUNT(*) * 100,2) as discount_rate
from sales_table
group by item_purchased
order by discount_rate desc
limit 5;


-- Q.7 Segement customers inot New, Returining and loyal based on thier total 
-- numeber of previous purchases, and show the count of each segment  

with customer_type as (
select customer_id, previous_purchases,
CASE 
	WHEN previous_purchases =1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
from sales_table
)
select customer_segment, count(*) as 'Number of Coustomers'
from customer_type
group by customer_segment;


-- Q.8 what are the top 3 most purchased products within each category?
with item_counts as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
Row_Number() over(partition by category order by count(customer_id) DESC) as item_rank 
from sales_table 
group by category, item_purchased
)
select item_rank , category, item_purchased, total_orders
from item_counts
where item_rank <=3;


-- Q.9 Are customers who are repeat buyers (more than 5 prevois purchaes) aslo likely to subscribe?

select 




















